# Site settings
remote_theme : midzer/urban-theme


title: something for nothing
email: raesaeng@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/works" # the subpath of your site, e.g. /blog
url: "http://raesaeng.github.io" # the base hostname & protocol for your site
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
twitter_username: 
github_username:  
  
# Build settings
markdown: kramdown
permalink: pretty
